language: c
dist: xenial

addons:
  apt:
    packages:
     - cmake
     - yasm
  homebrew:
    packages:
      - yasm

jobs:
  include:
   # General Linux build job
   - name: Build
     script:
     - ./Build/linux/build.sh release
